server:
  port: 9099
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/com/mapper/*.xml
spring:
  shardingsphere:
    datasource:
      names: master0,slave0,slave1
      master0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:9902/user_db?characterEncoding=utf-8
        username: root
        password: mysql
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:9901/user_db?characterEncoding=utf-8
        username: root
        password: mysql
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:9903/user_db?characterEncoding=utf-8
        username: root
        password: mysql
    # 读写分离
    sharding:
      master-slave-rules:
        master0:
          master-data-source-name: master0
          slave-data-source-names: slave0,slave1
          load-balance-algorithm-type: round_robin
      binding-tables: t_order
      tables:
        t_order:
          actual-data-nodes: master0.t_order_$->{0..1}
          table-strategy:
            inline:
              algorithm-expression: t_order_$->{order_id % 2} # 分表的算法表达式
              sharding-column: order_id  #根据order_id进行分表


    # 打印日志
    props:
      show:
        sql: true
