server:
  port: 9099

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/com/mapper/*.xml

spring:
  shardingsphere:
    datasource:
      names: master
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/user_db?characterEncoding=utf-8
        username: root
        password: mysql
    sharding:
      binding-tables: t_order
      tables:
        t_order:
          actual-data-nodes: master.t_order_$->{0..2}
          table-strategy:
            inline:
              algorithm-expression: t_order_$->{order_id % 3} # 分表的算法表达式
              sharding-column: order_id  #根据order_id进行分表
    # 显示日志
    props:
      show:
        sql: true


